### ISSUE TITLE
Can't have case as the last expression

### ISSUE THREAD

**Issue by tzbob** [kwanghoon/genlrparser#3]
I found out that whenever I have case expressions as the last expression I get the following error: 
```polyrpc-exe: Not found in the action table: $ at (6, 1): $ : (6,"$")
CallStack (from HasCallStack):
  error, called at src/parserlib/CommonParserUtil.hs:203:11 in genlrparser-0.1.0.0-94uLv9mXElrJeWoLxfW0Mm:CommonParserUtil
```
Example file: [regression_1.rl](https://github.com/kwanghoon/genlrparser/files/4353039/regression_1.rl.txt)

```
data F = { F Int };

main : Int = case (F 5) {
  F i => i
};
```

**Comment by kwanghoon** [comment]
@tzbob Thanks for pointing this out. 

You should omit the last semicolon after the case expression. Semicolons are only allowed between two toplevel things. 

But interestingly, deleting the semicolon uncovered a bug in the typechecker. So I fixed it, and the new version is available in the commit 1ca9041


Thanks!!
