### ISSUE TITLE
Error parsing/typechecking Tuple in main

### ISSUE THREAD

**Issue by tzbob** [kwanghoon/genlrparser#4]
```main : (Int, Int) = (5, 20)```

Causes the following error:

```polyrpc-exe: No match in record selector fromASTExprSeq```

**Comment by kwanghoon** [comment]
@tzbob 
Thanks for reporting this!! Fixed at #42c5add

**Comment by kwanghoon** [comment]
@tzbob 
I have addes a tuple example: genlrparser/app/polyrpc/examples/tuple.rl
after I revising the parser and the type checker for case alternatives over tuples.
Thanks!!
