### ISSUE TITLE
Strings in the Json AST contain string delimiters

### ISSUE THREAD

**Issue by tzbob** [kwanghoon/genlrparser#5]
Not sure if this is intended behavior so thought I'd check. 

For example: 

```
y : Unit = x := {server client} [String] "four five six" ;
```

Produces a Json AST containing:
```
 {"Lit": {"StrLit": "\"four five six\""}},
```

I'm not sure if this is a parser thing (where it includes the " string delimiter as part of the string, or a Json encoding issue or just intended behavior, but I was expecting "StrLit": "four five six" instead.

**Comment by kwanghoon** [comment]
@tzbob it is the Json writer library that I used who write strings including double quotation marks as well. If strings in the Json files consistently contains double quotation marks, you can safely ignore them. :)
